- name: Copy files using rsync
  hosts: localhost
  gather_facts: yes
  # vars:
  #   ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'  # DO NOT USE IN PRODUCTION ENVIRONMENT (auto accept hosts fingerprints)

  tasks:
    - name: Include rsync copy role
      include_role:
        name: rsync_copy
