#!/bin/bash
### DO NOT USE KEYS GENERATED BY THIS SCRIPT IN PRODUCTION
mkdir -p ssh_keys
# create key without password
ssh-keygen -t rsa -b 4096 -f ssh_keys/id_rsa -C "copy@testing" -N ""
cat ssh_keys/id_rsa.pub > ssh_keys/authorized_keys